version: 2
updates:
  # Gradle & Version Catalog updates
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
