sonar.organization=arrase
sonar.projectKey=arrase_Geotify
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacoco.xml
sonar.java.binaries=app/build/intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes
