sonar.organization=arrase
sonar.projectKey=arrase_Geotify
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacoco.xml
sonar.java.binaries=app/build/intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes
sonar.coverage.exclusions=**/ui/component/**,**/ui/screen/*Screen.kt,**/ui/theme/**,**/ui/navigation/**,**/*Activity.kt,**/*Application.kt,**/di/**,**/permission/**,**/data/*Database.kt,**/geofence/AndroidGeofenceManager.kt,**/geofence/BootCompletedReceiver.kt,**/geofence/GeofenceBroadcastReceiver.kt,**/geofence/GeofenceRecalculationWorker.kt,**/notification/**,**/location/**,**/util/**
